"""add tables

Revision ID: 407dfc32fa62
Revises: 
Create Date: 2022-12-07 19:02:58.259237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407dfc32fa62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Integer(), nullable=False),
                    sa.Column('image_url', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('avatar_url', sa.String(), nullable=True),
                    sa.Column('hash_password', sa.String(), nullable=False),
                    sa.Column('progress', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('word',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('word', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('attempt',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userId', sa.Integer(), nullable=True),
                    sa.Column('wordId', sa.Integer(), nullable=True),
                    sa.Column('attempt', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['wordId'], ['word.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_achievement',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userId', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_achievement')
    op.drop_table('attempt')
    op.drop_table('word')
    op.drop_table('user')
    op.drop_table('achievement')
    # ### end Alembic commands ###
