"""changed progress column name in user table

Revision ID: af134fc51ebb
Revises: 24e8ca843a8c
Create Date: 2022-12-15 17:27:38.677112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af134fc51ebb'
down_revision = '24e8ca843a8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_word_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'word', ['current_word_id'], ['id'])
    op.drop_column('user', 'progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'current_word_id')
    # ### end Alembic commands ###
